version: "2"
services:
  web:
    build: .
    ports:
    - "5002:5000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - D:/Ganu/Codes/nodeintern/data/:/data/db